#постоянно добавляет эти флаги при запуске. т.е. в терминал не пиши 

[pytest]
addopts = -s -v 
python_files=test_*.py 
python_classes=Test*
python_functions=test_*

markers =
    ui: Маркировка для тестов
    smoke: Маркировка для смоук тестов 
    regression: Маркировка для регресионных тестов
    slow: Маркировка для медленных тестов
    critical: Маркировка для критичных тестов
    dashboard: Маркировка для тестов рабочей панели
    registration: Маркировка для регистрационных тестов
    authorization: Маркировка для тестов авторизации
    courses: Маркировка для тестов по курсам 
    